// Generated by Dagger (https://dagger.dev).
package com.shaheer.adecadeofmovies.ui.movieadapter;

import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class MoviesAdapter_Factory implements Factory<MoviesAdapter> {
  private final Provider<MovieClickListener> movieClickListenerProvider;

  public MoviesAdapter_Factory(Provider<MovieClickListener> movieClickListenerProvider) {
    this.movieClickListenerProvider = movieClickListenerProvider;
  }

  @Override
  public MoviesAdapter get() {
    return newInstance(movieClickListenerProvider.get());
  }

  public static MoviesAdapter_Factory create(
      Provider<MovieClickListener> movieClickListenerProvider) {
    return new MoviesAdapter_Factory(movieClickListenerProvider);
  }

  public static MoviesAdapter newInstance(MovieClickListener movieClickListener) {
    return new MoviesAdapter(movieClickListener);
  }
}
