// Generated by Dagger (https://dagger.dev).
package com.shaheer.adecadeofmovies.data.remote.getmovies;

import android.content.Context;
import com.google.gson.Gson;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class GetMoviesData_Factory implements Factory<GetMoviesData> {
  private final Provider<Context> contextProvider;

  private final Provider<Gson> gsonProvider;

  public GetMoviesData_Factory(Provider<Context> contextProvider, Provider<Gson> gsonProvider) {
    this.contextProvider = contextProvider;
    this.gsonProvider = gsonProvider;
  }

  @Override
  public GetMoviesData get() {
    return newInstance(contextProvider.get(), gsonProvider.get());
  }

  public static GetMoviesData_Factory create(Provider<Context> contextProvider,
      Provider<Gson> gsonProvider) {
    return new GetMoviesData_Factory(contextProvider, gsonProvider);
  }

  public static GetMoviesData newInstance(Context context, Gson gson) {
    return new GetMoviesData(context, gson);
  }
}
